<a href="https://colab.research.google.com/github/angeliki-tzanou/sqlite_database_operations/blob/main/Assignment_3_HHA_504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Datasets:

In [1]:
import pandas as pd

In [11]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
import seaborn as sns



> Data set #1:

In [5]:
df_3= pd.read_csv("stonybrook.csv")

In [6]:
df_3.head(10)

,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
0,10004,"FINE NEEDLE ASPIRATION BIOPSY, EACH ADDITIONAL...",Outpatient,Line,718.67,718.67,2155.50,2155.50,2155.50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,2061.25,2061.25,87.02,4782.00,2308.44,2411.0,...,NaN,4782.0,NaN,NaN,3845.25,NaN,NaN,658.94,NaN,NaN
2,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Package,2061.25,2061.25,87.02,4782.00,2308.44,2411.0,...,NaN,4782.0,NaN,NaN,3845.25,NaN,NaN,658.94,NaN,NaN
3,10006,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,728.54,728.54,58.55,1761.25,909.90,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,2823.01,2823.01,446.28,6017.59,4219.31,4592.0,...,NaN,NaN,NaN,NaN,5127.00,NaN,NaN,NaN,NaN,NaN
5,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Package,2823.01,2823.01,446.28,6017.59,4219.31,4592.0,...,NaN,NaN,NaN,NaN,5127.00,NaN,NaN,NaN,NaN,NaN
6,10010,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,588.00,588.00,2155.50,2155.50,2155.50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Line,1566.78,1566.78,275.46,2265.50,1270.48,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Package,1566.78,1566.78,275.46,2265.50,1270.48,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10030,DRAINAGE OF FLUID COLLECTION IN SOFT TISSUE US...,Outpatient,Line,2082.05,2082.05,152.66,4101.00,1663.85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###Defining the numerical columns in the dataset to perform some data analysis:



> Replacing NaN values with the mean of the numerical columns to perform some basic statistical analysis and derive more accurate results:

In [ ]:
df_3.fillna(df_3.mean(), inplace=True)

In [14]:
df_3.head(10)

,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
0,10004,"FINE NEEDLE ASPIRATION BIOPSY, EACH ADDITIONAL...",Outpatient,Line,718.67,718.67,2155.50,2155.50,2155.50,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
1,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,2061.25,2061.25,87.02,4782.00,2308.44,2411.000000,...,10868.205705,4782.000000,NaN,2070.21212,3845.250000,4438.776234,3261.594586,658.940000,789.416667,702.261087
2,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Package,2061.25,2061.25,87.02,4782.00,2308.44,2411.000000,...,10868.205705,4782.000000,NaN,2070.21212,3845.250000,4438.776234,3261.594586,658.940000,789.416667,702.261087
3,10006,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,728.54,728.54,58.55,1761.25,909.90,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
4,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,2823.01,2823.01,446.28,6017.59,4219.31,4592.000000,...,10868.205705,2572.653849,NaN,2070.21212,5127.000000,4438.776234,3261.594586,2454.314228,789.416667,702.261087
5,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Package,2823.01,2823.01,446.28,6017.59,4219.31,4592.000000,...,10868.205705,2572.653849,NaN,2070.21212,5127.000000,4438.776234,3261.594586,2454.314228,789.416667,702.261087
6,10010,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,588.00,588.00,2155.50,2155.50,2155.50,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Line,1566.78,1566.78,275.46,2265.50,1270.48,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
8,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Package,1566.78,1566.78,275.46,2265.50,1270.48,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
9,10030,DRAINAGE OF FLUID COLLECTION IN SOFT TISSUE US...,Outpatient,Line,2082.05,2082.05,152.66,4101.00,1663.85,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087



>  Replacing NaN values with the mode of the categorical columns(if they have one) to perform some basic statistical analysis and derive more accurate results:

In [15]:
df_3.columns

Index(['Code', 'Description', 'Type', 'Package/Line_Level', 'Gross charge',
       'Discounted cash price', 'De-identified min contracted rate',
       'De-identified max contracted rate', 'Derived contracted rate',
       '1199-Commercial other', 'Aetna-Medicare Advantage HMO',
       'Aetna-Commercial HMO/POS', 'Aetna-Commercial PPO/Open Access',
       'Aetna-Commercial other', 'Empire Health-Commercial other',
       'Empire Health-Commercial PPO/Open Access',
       'BlueCross BlueShield-Commercial other',
       'Beacon Health-Commercial other', 'Carelon Health-Commercial other',
       'Cigna-Commercial PPO/Open Access', 'Cigna-Commercial other',
       'Cigna-Commercial HMO/POS', 'EH Facet-Commercial other',
       'EmblemHealth-Commercial PPO/Open Access',
       'EmblemHealth-Commercial other', 'EmblemHealth-Commercial HMO/POS',
       'EmblemHealth-Medicaid HMO', 'EmblemHealth-Medicare Advantage HMO',
       'Empire Health-Commercial HMO/POS',
       'Empire Health-Medicare Advantage HMO', 'Empire Health-Medicaid HMO',
       'Evernorth-Commercial other', 'Fidelis-Commercial other',
       'Fidelis-Medicare Advantage HMO', 'Fidelis-Medicaid HMO',
       'GHI-Commercial other', 'HealthFirst-Commercial other',
       'HealthFirst-Medicare Advantage HMO', 'HealthFirst-Medicaid HMO',
       'HealthPlus HP-Medicaid HMO', 'HealthPlus HP-Commercial other',
       'HealthPlus HP-Medicare Advantage HMO', 'Humana-Commercial other',
       'Humana-Commercial HMO/POS', 'Humana-Commercial PPO/Open Access',
       'Meritain Health-Commercial other', 'Molina-Commercial other',
       'Optum-Commercial other', 'Oxford-Commercial other',
       'Oxford-Commercial HMO/POS', 'Tricare-Commercial other',
       'United Healthcare-Commercial other',
       'United Healthcare-Medicare Advantage HMO',
       'United Healthcare-Commercial HMO/POS',
       'United Healthcare-Medicaid HMO',
       'United Healthcare-Commercial PPO/Open Access',
       'Veteran Family-Commercial other'],
      dtype='object')

In [16]:
categorical_col = df_3.select_dtypes(include=['category']).columns

In [17]:
for col in categorical_col:
  mode = df_3[col].mode()[0]
  df_3[col].fillna(mode, inplace=True)

In [18]:
df_3.head(10)

,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
0,10004,"FINE NEEDLE ASPIRATION BIOPSY, EACH ADDITIONAL...",Outpatient,Line,718.67,718.67,2155.50,2155.50,2155.50,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
1,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,2061.25,2061.25,87.02,4782.00,2308.44,2411.000000,...,10868.205705,4782.000000,NaN,2070.21212,3845.250000,4438.776234,3261.594586,658.940000,789.416667,702.261087
2,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Package,2061.25,2061.25,87.02,4782.00,2308.44,2411.000000,...,10868.205705,4782.000000,NaN,2070.21212,3845.250000,4438.776234,3261.594586,658.940000,789.416667,702.261087
3,10006,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,728.54,728.54,58.55,1761.25,909.90,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
4,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,2823.01,2823.01,446.28,6017.59,4219.31,4592.000000,...,10868.205705,2572.653849,NaN,2070.21212,5127.000000,4438.776234,3261.594586,2454.314228,789.416667,702.261087
5,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Package,2823.01,2823.01,446.28,6017.59,4219.31,4592.000000,...,10868.205705,2572.653849,NaN,2070.21212,5127.000000,4438.776234,3261.594586,2454.314228,789.416667,702.261087
6,10010,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,588.00,588.00,2155.50,2155.50,2155.50,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Line,1566.78,1566.78,275.46,2265.50,1270.48,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
8,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Package,1566.78,1566.78,275.46,2265.50,1270.48,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
9,10030,DRAINAGE OF FLUID COLLECTION IN SOFT TISSUE US...,Outpatient,Line,2082.05,2082.05,152.66,4101.00,1663.85,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087

In [19]:
df_3.tail(10)

,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
7700,30991053,R&B SICR 09W2 - PT-T,NaN,NaN,8165.0,8165.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7701,30991202,R&B SICR 09W2 - PT-Z,NaN,NaN,12090.0,12090.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7702,30984009,R&B SICU 09W1 - PT-I,NaN,NaN,13590.0,13590.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7703,30983001,R&B SICU 09W1 - PT-J,NaN,NaN,8165.0,8165.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7704,30981054,R&B SICU 09W1 - PT-T,NaN,NaN,8165.0,8165.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7705,30981203,R&B SICU 09W1 ICR PT-Z,NaN,NaN,12090.0,12090.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7706,30993018,R&B TICR 09W2 - PT-I,NaN,NaN,13590.0,13590.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7707,33500000,R&B REV PICU 11S2 PT-X,NaN,NaN,8165.0,8165.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7708,30333058,ROPH HOSP.OBSERVATION PT-T,NaN,NaN,8165.0,8165.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7709,30000004,SEMI-PRIVATE,NaN,NaN,8165.0,8165.0,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087

In [21]:
df_3.sample(10)

,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
5627,D9943,OCCLUSAL GUARD ADJUSTMENT,Outpatient,Line,3128.00,3128.00,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
4272,82626,DEHYDROEPIANDROSTERONE (DHEA) HORMONE LEVEL,Outpatient,Line,30.00,30.00,13.500000,18.360000,15.930000,5791.542456,...,10868.205705,18.360000,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
2940,60280,REMOVAL OF CYST OF THYROID OR DRAINAGE OF THYR...,Outpatient,Package,10823.48,10823.48,2857.460000,6385.200000,4636.800000,5791.542456,...,10868.205705,4782.000000,NaN,2070.21212,4704.000000,4438.776234,3261.594586,2454.314228,789.416667,702.261087
1476,31287,INCISION OF SPHENOID NASAL SINUS USING AN ENDO...,Outpatient,Package,7468.60,7468.60,1751.420000,8530.690000,5141.060000,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
7577,30323000,R&B REV EMER 04PT PT-J,NaN,NaN,8165.00,8165.00,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
3690,73564,"X-RAY OF KNEE, 4 OR MORE VIEWS",Outpatient,Line,976.29,976.29,20.000000,967.270000,431.090000,631.260000,...,10868.205705,695.640000,NaN,125.91000,765.380000,125.070000,3261.594586,20.000000,877.630000,702.261087
2975,62304,X-RAY OF LOWER SPINAL CANAL WITH REVIEW BY RAD...,Outpatient,Line,3122.67,3122.67,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
4445,85045,"RED BLOOD COUNT, AUTOMATED TEST",Outpatient,Line,77.85,77.85,3.170000,77.560000,30.930000,47.200000,...,10868.205705,55.760000,NaN,4.94000,58.520000,3.990000,3261.594586,3.230000,6.020000,702.261087
838,26236,PARTIAL REMOVAL OF FINGER BONE AT END OF FINGER,Outpatient,Line,3287.11,3287.11,4090.693876,10035.793743,6315.587725,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
6016,Q5101,"INJECTION, FILGRASTIM-SNDZ, BIOSIMILAR, (ZARXI...",Outpatient,Line,1.76,1.76,0.230000,1.150000,0.730000,5791.542456,...,10868.205705,2572.653849,NaN,2070.21212,0.270000,4438.776234,3261.594586,1.050000,789.416667,702.261087



> Descriptive Statistics below for numerical columns:

In [22]:
numerical_col = df_3.select_dtypes(include=['int','float'])

In [23]:
num_stats= numerical_col.describe()
print(num_stats)

       Gross charge  Discounted cash price  De-identified min contracted rate  \
count  7.710000e+03           7.710000e+03                        7710.000000
mean   2.274832e+04           2.274832e+04                        4090.693876
std    7.470570e+04           7.470570e+04                        9525.228459
min    3.000000e-02           3.000000e-02                           0.010000
25%    1.065895e+03           1.065895e+03                         159.387500
50%    4.745295e+03           4.745295e+03                        2186.810000
75%    1.103881e+04           1.103881e+04                        4090.693876
max    1.857952e+06           1.857952e+06                      327869.690000

       De-identified max contracted rate  Derived contracted rate  \
count                       7.710000e+03              7710.000000
mean                        1.003579e+04              6315.587725
std                         2.625396e+04             13150.824055
min                         1.000000e-01                 0.030000
25%                         1.381910e+03               733.145000
50%                         5.975000e+03              3941.050000
75%                         1.003579e+04              6315.587725
max                         1.302636e+06            370099.900000

       1199-Commercial other  Aetna-Medicare Advantage HMO  \
count            7710.000000                   7710.000000
mean             5791.542456                   5614.005027
std              8809.555867                   4797.441805
min                 0.010000                      1.100000
25%              5791.542456                   5614.005027
50%              5791.542456                   5614.005027
75%              5791.542456                   5614.005027
max            331304.280000                 157848.600000

       Aetna-Commercial HMO/POS  Aetna-Commercial PPO/Open Access  \
count               7710.000000                       7710.000000
mean                4320.418248                       4436.188381
std                 4243.214513                       4060.191371
min                    0.020000                          0.500000
25%                 4320.418248                       4436.188381
50%                 4320.418248                       4436.188381
75%                 4320.418248                       4436.188381
max                99999.990000                      96372.570000

       Aetna-Commercial other  ...  Optum-Commercial other  \
count             7710.000000  ...             7710.000000
mean              1703.756250  ...            10868.205705
std                657.705827  ...             7237.169013
min                  0.590000  ...                2.370000
25%               1703.756250  ...            10868.205705
50%               1703.756250  ...            10868.205705
75%               1703.756250  ...            10868.205705
max              54838.130000  ...           277267.380000

       Oxford-Commercial other  Oxford-Commercial HMO/POS  \
count              7710.000000                        0.0
mean               2572.653849                        NaN
std                1937.516570                        NaN
min                   0.010000                        NaN
25%                2572.653849                        NaN
50%                2572.653849                        NaN
75%                2572.653849                        NaN
max               80891.260000                        NaN

       Tricare-Commercial other  United Healthcare-Commercial other  \
count               7710.000000                         7710.000000
mean                2070.212120                         5977.464298
std                 2014.775327                         8971.253405
min                    1.000000                            0.010000
25%                 2070.212120                         5127.000000
50%                 2070.212120                         5977.464298
75%                 2070.212120                         5977.464298
max               154940.610000                       291490.750000

       United Healthcare-Medicare Advantage HMO  \
count                               7710.000000
mean                                4438.776234
std                                 2837.839114
min                                    1.330000
25%                                 4438.776234
50%                                 4438.776234
75%                                 4438.776234
max                                92493.910000

       United Healthcare-Commercial HMO/POS  United Healthcare-Medicaid HMO  \
count                           7710.000000                     7710.000000
mean                            3261.594586                     2454.314228
std                             1343.412645                     5696.514943
min                                0.190000                        0.010000
25%                             3261.594586                     2454.314228
50%                             3261.594586                     2454.314228
75%                             3261.594586                     2454.314228
max                            88051.340000                   327869.690000

       United Healthcare-Commercial PPO/Open Access  \
count                                   7710.000000
mean                                     789.416667
std                                      619.001740
min                                        0.180000
25%                                      789.416667
50%                                      789.416667
75%                                      789.416667
max                                    26350.000000

       Veteran Family-Commercial other
count                      7710.000000
mean                        702.261087
std                         131.183451
min                           2.480000
25%                         702.261087
50%                         702.261087
75%                         702.261087
max                        7195.400000

[8 rows x 53 columns]



> Frequency counts for categorical columns:

- Creating a dictionary to store the frequency counts data throughout this loop command below

In [25]:
frequency_counts = {}
cat_col = df_3.select_dtypes(include=['object','category']).columns

for col in cat_col:
  frequency_counts[col] = df_3[col].value_counts()

In [33]:
for col, counts in frequency_counts.items():
  print(f"Frequency counts for '{col}':")
  print(counts)
  print()

Frequency counts for 'Code':
73521       2
64600       2
64454       2
64461       2
64483       2
           ..
C1727       1
C1728       1
C1729       1
C1730       1
30000004    1
Name: Code, Length: 5474, dtype: int64

Frequency counts for 'Description':
R&B MED 05CA SEMI-PRIVATE/2                                                                   3
R&B SHA 05PS/11PS SEMI-PRIVATE                                                                3
DESTRUCTION OF FIRST DIVISION OF FACE NERVE BRANCH                                            2
INJECTION OF CHEMICAL FOR PARALYSIS OF SALIVARY GLANDS ON BOTH SIDES OF MOUTH                 2
INJECTION OF CHEMICAL FOR PARALYSIS OF FACIAL AND NECK NERVE MUSCLES ON BOTH SIDES OF FACE    2
                                                                                             ..
ANCHOR/SCREW FOR OPPOSING BONE-TO-BONE OR SOFT TISSUE-TO-BONE (IMPLANTABLE)                   1
BRACHYTHERAPY NEEDLE                                                                          1
CARDIOVERTER-DEFIBRILLATOR, DUAL CHAMBER (IMPLANTABLE)                                        1
CARDIOVERTER-DEFIBRILLATOR, SINGLE CHAMBER (IMPLANTABLE)                                      1
SEMI-PRIVATE                                                                                  1
Name: Description, Length: 5449, dtype: int64

Frequency counts for 'Type':
Outpatient    6041
Inpatient      886
Name: Type, dtype: int64

Frequency counts for 'Package/Line_Level':
Line       4691
Package    2236
Name: Package/Line_Level, dtype: int64

From the above analysis it was very interesting to observe the frequency of certain CPT codes and procedures. Additionally the fact the outpatient encounters severely outnumbered the inpatient ones, was also very insightful, especially when various of the procedures would be considered highly complex.



> Dataset #2:

In [6]:
df_3= pd.read_json("nypdata.json"